[build]
  base    = "project"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"

[functions]
  directory = "netlify/functions"
